// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solve.FinancialMarketIntegration.API.Areas.Files.Infrastructure.DataAccess;

namespace Solve.FinancialMarketIntegration.API.Areas.Files.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(FileDataContext))]
    [Migration("20190604184057_0.0.0.1")]
    partial class _0001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.Files.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .IsUnicode(false);

                    b.Property<short>("IdFileType")
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<short>("Status")
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Files","Files");
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.Files.Entities.FilePESC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<string>("AssetCode");

                    b.Property<string>("BrokerCode");

                    b.Property<string>("BuyOrSell");

                    b.Property<string>("ClientCode");

                    b.Property<string>("ClientCodeDigit");

                    b.Property<string>("CompanyName");

                    b.Property<string>("CustodianClientCode");

                    b.Property<string>("CustodianClientCodeDigit");

                    b.Property<string>("CustodianUserCode");

                    b.Property<DateTime>("DateFile");

                    b.Property<DateTime>("DateMarket");

                    b.Property<int>("Factor");

                    b.Property<string>("ISINCode");

                    b.Property<string>("ISINCodeDistribution");

                    b.Property<int>("IdFile");

                    b.Property<string>("IsAfterMarket");

                    b.Property<string>("MarketType");

                    b.Property<string>("PortfolioCode");

                    b.Property<string>("PortfolioCodeDigit");

                    b.Property<decimal>("Price");

                    b.Property<string>("SettlementType");

                    b.Property<string>("SettlementTypeOfSecondaryTerm");

                    b.Property<string>("Specification");

                    b.Property<string>("SpecificationIndicator");

                    b.Property<string>("StockExchangeCode");

                    b.Property<string>("TradingCode");

                    b.Property<string>("TradingCodeBusinessCode");

                    b.HasKey("Id");

                    b.ToTable("FilesPESC","Files");
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.Files.Entities.FileType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Type","Files");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "NEGS"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "PESQ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
