FROM alpine/git AS git-env
WORKDIR /app

RUN git clone -b develop https://cddlutkzlywfcooqu3xmprrerc2lagvsjpzbajmjcow46oq7t67a@dev.azure.com/itlabbrasil/Solve.FinancialMarketIntegration.API/_git/Solve.FinancialMarketIntegration.API

FROM microsoft/dotnet:2.2-sdk-alpine AS build-env
WORKDIR /app

# Copiar csproj e restaurar dependencias
COPY --from=git-env /app/Solve.FinancialMarketIntegration.API/src/*.csproj ./
RUN dotnet restore

# Build da aplicacao
COPY --from=git-env /app/Solve.FinancialMarketIntegration.API/src/. ./
RUN dotnet publish -c Release -o out

# EF
COPY appsettings.json ./

#DB
RUN rm -rf Areas/Tickets/Infrastructure/DataAccess/Migrations
RUN rm -rf Areas/Security/Infrastructure/DataAccess/Migrations
RUN rm -rf Areas/WK/Infrastructure/DataAccess/Migrations
RUN rm -rf Areas/Files/Infrastructure/DataAccess/Migrations

RUN dotnet ef migrations add 0.0.0.1 --context Solve.FinancialMarketIntegration.API.Areas.Tickets.Infrastructure.DataAccess.TicketDataContext -o Areas/Tickets/Infrastructure/DataAccess/Migrations
RUN dotnet ef migrations add 0.0.0.1 --context Solve.FinancialMarketIntegration.API.Areas.Security.Infrastructure.DataAccess.DataContext -o Areas/Security/Infrastructure/DataAccess/Migrations
RUN dotnet ef migrations add 0.0.0.1 --context Solve.FinancialMarketIntegration.API.Areas.WK.Infrastructure.DataAccess.WfDataContext -o Areas/WK/Infrastructure/DataAccess/Migrations
RUN dotnet ef migrations add 0.0.0.1 --context Solve.FinancialMarketIntegration.API.Areas.Files.Infrastructure.DataAccess.FileDataContext -o Areas/Files/Infrastructure/DataAccess/Migrations

RUN dotnet ef database update --context Solve.FinancialMarketIntegration.API.Areas.Tickets.Infrastructure.DataAccess.TicketDataContext
RUN dotnet ef database update --context Solve.FinancialMarketIntegration.API.Areas.Security.Infrastructure.DataAccess.DataContext
RUN dotnet ef database update --context Solve.FinancialMarketIntegration.API.Areas.WK.Infrastructure.DataAccess.WfDataContext
RUN dotnet ef database update --context Solve.FinancialMarketIntegration.API.Areas.Files.Infrastructure.DataAccess.FileDataContext


