// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solve.FinancialMarketIntegration.API.Areas.WK.Infrastructure.DataAccess;

namespace Solve.FinancialMarketIntegration.API.Areas.WK.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(WorkflowDataContext))]
    [Migration("20190726211108_1.0.0.5")]
    partial class _1005
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("ChangeDate");

                    b.Property<string>("ChangeUser");

                    b.Property<DateTimeOffset>("CreationDate");

                    b.Property<string>("CreationUser");

                    b.Property<int?>("CurrentStepId");

                    b.Property<DateTimeOffset?>("EndDate");

                    b.Property<bool>("IsFinished");

                    b.Property<DateTimeOffset>("StartDate");

                    b.Property<int>("WorkflowTypeId");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStepId");

                    b.HasIndex("WorkflowTypeId");

                    b.ToTable("Workflow","Workflow");
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("ChangeDate");

                    b.Property<string>("ChangeUser");

                    b.Property<DateTimeOffset>("CreationDate");

                    b.Property<string>("CreationUser");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Approval","Workflow");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Gestores"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Administração Fiduciária"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Open"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Custódia"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Middle Adim"
                        });
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApprovalRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApprovalId");

                    b.Property<DateTimeOffset?>("ChangeDate");

                    b.Property<string>("ChangeUser");

                    b.Property<DateTimeOffset>("CreationDate");

                    b.Property<string>("CreationUser");

                    b.Property<int>("RoleId");

                    b.Property<int?>("WorkflowApprovalStepId");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalId");

                    b.HasIndex("WorkflowApprovalStepId");

                    b.ToTable("ApprovalRole","Workflow");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalId = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 10,
                            WorkflowApprovalStepId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 11,
                            WorkflowApprovalStepId = 2
                        },
                        new
                        {
                            Id = 3,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 12,
                            WorkflowApprovalStepId = 4
                        },
                        new
                        {
                            Id = 4,
                            ApprovalId = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 10,
                            WorkflowApprovalStepId = 7
                        },
                        new
                        {
                            Id = 5,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 11,
                            WorkflowApprovalStepId = 8
                        },
                        new
                        {
                            Id = 6,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 12,
                            WorkflowApprovalStepId = 10
                        },
                        new
                        {
                            Id = 7,
                            ApprovalId = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 10,
                            WorkflowApprovalStepId = 13
                        },
                        new
                        {
                            Id = 8,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 11,
                            WorkflowApprovalStepId = 14
                        },
                        new
                        {
                            Id = 9,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 12,
                            WorkflowApprovalStepId = 16
                        },
                        new
                        {
                            Id = 10,
                            ApprovalId = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 10,
                            WorkflowApprovalStepId = 19
                        },
                        new
                        {
                            Id = 11,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 11,
                            WorkflowApprovalStepId = 20
                        },
                        new
                        {
                            Id = 12,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 12,
                            WorkflowApprovalStepId = 22
                        },
                        new
                        {
                            Id = 13,
                            ApprovalId = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 10,
                            WorkflowApprovalStepId = 25
                        },
                        new
                        {
                            Id = 14,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 11,
                            WorkflowApprovalStepId = 26
                        },
                        new
                        {
                            Id = 15,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 12,
                            WorkflowApprovalStepId = 28
                        },
                        new
                        {
                            Id = 16,
                            ApprovalId = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 10,
                            WorkflowApprovalStepId = 31
                        },
                        new
                        {
                            Id = 17,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 11,
                            WorkflowApprovalStepId = 32
                        },
                        new
                        {
                            Id = 18,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 12,
                            WorkflowApprovalStepId = 34
                        },
                        new
                        {
                            Id = 19,
                            ApprovalId = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 10,
                            WorkflowApprovalStepId = 37
                        },
                        new
                        {
                            Id = 20,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 11,
                            WorkflowApprovalStepId = 38
                        },
                        new
                        {
                            Id = 21,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 12,
                            WorkflowApprovalStepId = 40
                        },
                        new
                        {
                            Id = 22,
                            ApprovalId = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 10,
                            WorkflowApprovalStepId = 43
                        },
                        new
                        {
                            Id = 23,
                            ApprovalId = 5,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 13,
                            WorkflowApprovalStepId = 44
                        },
                        new
                        {
                            Id = 24,
                            ApprovalId = 5,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 14,
                            WorkflowApprovalStepId = 46
                        },
                        new
                        {
                            Id = 25,
                            ApprovalId = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 10,
                            WorkflowApprovalStepId = 49
                        },
                        new
                        {
                            Id = 26,
                            ApprovalId = 4,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 15,
                            WorkflowApprovalStepId = 50
                        },
                        new
                        {
                            Id = 27,
                            ApprovalId = 4,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 16,
                            WorkflowApprovalStepId = 52
                        },
                        new
                        {
                            Id = 28,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 11,
                            WorkflowApprovalStepId = 53
                        },
                        new
                        {
                            Id = 29,
                            ApprovalId = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 12,
                            WorkflowApprovalStepId = 55
                        },
                        new
                        {
                            Id = 30,
                            ApprovalId = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 10,
                            WorkflowApprovalStepId = 58
                        },
                        new
                        {
                            Id = 31,
                            ApprovalId = 4,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 15,
                            WorkflowApprovalStepId = 59
                        },
                        new
                        {
                            Id = 32,
                            ApprovalId = 4,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 16,
                            WorkflowApprovalStepId = 61
                        },
                        new
                        {
                            Id = 33,
                            ApprovalId = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 10,
                            WorkflowApprovalStepId = 64
                        },
                        new
                        {
                            Id = 34,
                            ApprovalId = 4,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 15,
                            WorkflowApprovalStepId = 65
                        },
                        new
                        {
                            Id = 35,
                            ApprovalId = 4,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 16,
                            WorkflowApprovalStepId = 67
                        },
                        new
                        {
                            Id = 36,
                            ApprovalId = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 10,
                            WorkflowApprovalStepId = 70
                        },
                        new
                        {
                            Id = 37,
                            ApprovalId = 4,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 15,
                            WorkflowApprovalStepId = 71
                        },
                        new
                        {
                            Id = 38,
                            ApprovalId = 4,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 16,
                            WorkflowApprovalStepId = 73
                        },
                        new
                        {
                            Id = 39,
                            ApprovalId = 1,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            RoleId = 27,
                            WorkflowApprovalStepId = 76
                        });
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApprovalStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("ChangeDate");

                    b.Property<string>("ChangeUser");

                    b.Property<DateTimeOffset>("CreationDate");

                    b.Property<string>("CreationUser");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsFirstStep");

                    b.Property<int?>("NextStepApprovedId");

                    b.Property<int?>("NextStepRejectedId");

                    b.Property<short?>("WorkflowStatusId");

                    b.Property<int?>("WorkflowTypeId");

                    b.HasKey("Id");

                    b.HasIndex("NextStepApprovedId");

                    b.HasIndex("NextStepRejectedId");

                    b.HasIndex("WorkflowStatusId");

                    b.HasIndex("WorkflowTypeId");

                    b.ToTable("ApprovalStep","Workflow");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)6,
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)5,
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)2,
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 5,
                            NextStepRejectedId = 6,
                            WorkflowStatusId = (short)4,
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 4,
                            NextStepRejectedId = 6,
                            WorkflowStatusId = (short)3,
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 2,
                            NextStepRejectedId = 3,
                            WorkflowStatusId = (short)1,
                            WorkflowTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)6,
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)5,
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)2,
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 11,
                            NextStepRejectedId = 12,
                            WorkflowStatusId = (short)4,
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 10,
                            NextStepRejectedId = 12,
                            WorkflowStatusId = (short)3,
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 8,
                            NextStepRejectedId = 9,
                            WorkflowStatusId = (short)1,
                            WorkflowTypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)6,
                            WorkflowTypeId = 3
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)5,
                            WorkflowTypeId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)2,
                            WorkflowTypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 17,
                            NextStepRejectedId = 18,
                            WorkflowStatusId = (short)4,
                            WorkflowTypeId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 16,
                            NextStepRejectedId = 18,
                            WorkflowStatusId = (short)3,
                            WorkflowTypeId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 14,
                            NextStepRejectedId = 15,
                            WorkflowStatusId = (short)1,
                            WorkflowTypeId = 3
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)6,
                            WorkflowTypeId = 4
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)5,
                            WorkflowTypeId = 4
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)2,
                            WorkflowTypeId = 4
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 23,
                            NextStepRejectedId = 24,
                            WorkflowStatusId = (short)4,
                            WorkflowTypeId = 4
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 22,
                            NextStepRejectedId = 24,
                            WorkflowStatusId = (short)3,
                            WorkflowTypeId = 4
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 20,
                            NextStepRejectedId = 21,
                            WorkflowStatusId = (short)1,
                            WorkflowTypeId = 4
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)6,
                            WorkflowTypeId = 5
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)5,
                            WorkflowTypeId = 5
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)2,
                            WorkflowTypeId = 5
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 29,
                            NextStepRejectedId = 30,
                            WorkflowStatusId = (short)4,
                            WorkflowTypeId = 5
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 28,
                            NextStepRejectedId = 30,
                            WorkflowStatusId = (short)3,
                            WorkflowTypeId = 5
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 26,
                            NextStepRejectedId = 27,
                            WorkflowStatusId = (short)1,
                            WorkflowTypeId = 5
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)6,
                            WorkflowTypeId = 6
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)5,
                            WorkflowTypeId = 6
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)2,
                            WorkflowTypeId = 6
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 35,
                            NextStepRejectedId = 36,
                            WorkflowStatusId = (short)4,
                            WorkflowTypeId = 6
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 34,
                            NextStepRejectedId = 36,
                            WorkflowStatusId = (short)3,
                            WorkflowTypeId = 6
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 32,
                            NextStepRejectedId = 33,
                            WorkflowStatusId = (short)1,
                            WorkflowTypeId = 6
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)6,
                            WorkflowTypeId = 7
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)5,
                            WorkflowTypeId = 7
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)2,
                            WorkflowTypeId = 7
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 41,
                            NextStepRejectedId = 42,
                            WorkflowStatusId = (short)4,
                            WorkflowTypeId = 7
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 40,
                            NextStepRejectedId = 42,
                            WorkflowStatusId = (short)3,
                            WorkflowTypeId = 7
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 38,
                            NextStepRejectedId = 39,
                            WorkflowStatusId = (short)1,
                            WorkflowTypeId = 7
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)6,
                            WorkflowTypeId = 8
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)5,
                            WorkflowTypeId = 8
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)2,
                            WorkflowTypeId = 8
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 47,
                            NextStepRejectedId = 48,
                            WorkflowStatusId = (short)11,
                            WorkflowTypeId = 8
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 46,
                            NextStepRejectedId = 48,
                            WorkflowStatusId = (short)10,
                            WorkflowTypeId = 8
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 44,
                            NextStepRejectedId = 45,
                            WorkflowStatusId = (short)1,
                            WorkflowTypeId = 8
                        },
                        new
                        {
                            Id = 57,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)9,
                            WorkflowTypeId = 9
                        },
                        new
                        {
                            Id = 54,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)6,
                            WorkflowTypeId = 9
                        },
                        new
                        {
                            Id = 56,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)5,
                            WorkflowTypeId = 9
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)2,
                            WorkflowTypeId = 9
                        },
                        new
                        {
                            Id = 55,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 56,
                            NextStepRejectedId = 54,
                            WorkflowStatusId = (short)4,
                            WorkflowTypeId = 9
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 55,
                            NextStepRejectedId = 54,
                            WorkflowStatusId = (short)3,
                            WorkflowTypeId = 9
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 53,
                            NextStepRejectedId = 57,
                            WorkflowStatusId = (short)14,
                            WorkflowTypeId = 9
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 52,
                            NextStepRejectedId = 57,
                            WorkflowStatusId = (short)13,
                            WorkflowTypeId = 9
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 50,
                            NextStepRejectedId = 51,
                            WorkflowStatusId = (short)1,
                            WorkflowTypeId = 9
                        },
                        new
                        {
                            Id = 63,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)9,
                            WorkflowTypeId = 10
                        },
                        new
                        {
                            Id = 62,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)5,
                            WorkflowTypeId = 10
                        },
                        new
                        {
                            Id = 60,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)2,
                            WorkflowTypeId = 10
                        },
                        new
                        {
                            Id = 61,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 62,
                            NextStepRejectedId = 63,
                            WorkflowStatusId = (short)8,
                            WorkflowTypeId = 10
                        },
                        new
                        {
                            Id = 59,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 61,
                            NextStepRejectedId = 63,
                            WorkflowStatusId = (short)7,
                            WorkflowTypeId = 10
                        },
                        new
                        {
                            Id = 58,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 59,
                            NextStepRejectedId = 60,
                            WorkflowStatusId = (short)1,
                            WorkflowTypeId = 10
                        },
                        new
                        {
                            Id = 69,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)9,
                            WorkflowTypeId = 11
                        },
                        new
                        {
                            Id = 68,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)5,
                            WorkflowTypeId = 11
                        },
                        new
                        {
                            Id = 66,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)2,
                            WorkflowTypeId = 11
                        },
                        new
                        {
                            Id = 67,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 68,
                            NextStepRejectedId = 69,
                            WorkflowStatusId = (short)8,
                            WorkflowTypeId = 11
                        },
                        new
                        {
                            Id = 65,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 67,
                            NextStepRejectedId = 69,
                            WorkflowStatusId = (short)7,
                            WorkflowTypeId = 11
                        },
                        new
                        {
                            Id = 64,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 65,
                            NextStepRejectedId = 66,
                            WorkflowStatusId = (short)1,
                            WorkflowTypeId = 11
                        },
                        new
                        {
                            Id = 75,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)9,
                            WorkflowTypeId = 12
                        },
                        new
                        {
                            Id = 74,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)5,
                            WorkflowTypeId = 12
                        },
                        new
                        {
                            Id = 72,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)2,
                            WorkflowTypeId = 12
                        },
                        new
                        {
                            Id = 73,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 74,
                            NextStepRejectedId = 75,
                            WorkflowStatusId = (short)8,
                            WorkflowTypeId = 12
                        },
                        new
                        {
                            Id = 71,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            NextStepApprovedId = 73,
                            NextStepRejectedId = 75,
                            WorkflowStatusId = (short)7,
                            WorkflowTypeId = 12
                        },
                        new
                        {
                            Id = 70,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 71,
                            NextStepRejectedId = 72,
                            WorkflowStatusId = (short)1,
                            WorkflowTypeId = 12
                        },
                        new
                        {
                            Id = 78,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)15,
                            WorkflowTypeId = 13
                        },
                        new
                        {
                            Id = 77,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = false,
                            WorkflowStatusId = (short)16,
                            WorkflowTypeId = 13
                        },
                        new
                        {
                            Id = 76,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            IsFirstStep = true,
                            NextStepApprovedId = 77,
                            NextStepRejectedId = 78,
                            WorkflowStatusId = (short)17,
                            WorkflowTypeId = 13
                        });
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApprovalStepResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApprovalId");

                    b.Property<DateTimeOffset?>("ChangeDate");

                    b.Property<string>("ChangeUser");

                    b.Property<string>("Comments");

                    b.Property<DateTimeOffset>("CreationDate");

                    b.Property<string>("CreationUser");

                    b.Property<bool?>("IsApproved");

                    b.Property<int>("RoleId");

                    b.Property<int?>("WorkflowStepResultId");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalId");

                    b.HasIndex("WorkflowStepResultId");

                    b.ToTable("ApprovalStepResult","Workflow");
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowStatus", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("ChangeDate");

                    b.Property<string>("ChangeUser");

                    b.Property<DateTimeOffset>("CreationDate");

                    b.Property<string>("CreationUser");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Status","Workflow");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Pendente de Aprovação pela ADM"
                        },
                        new
                        {
                            Id = (short)2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Cancelada pela ADM"
                        },
                        new
                        {
                            Id = (short)3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Aguardando Liquidação"
                        },
                        new
                        {
                            Id = (short)4,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Em Liquidação"
                        },
                        new
                        {
                            Id = (short)5,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Liquidada"
                        },
                        new
                        {
                            Id = (short)6,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Cancelada pela Liquidação"
                        },
                        new
                        {
                            Id = (short)7,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Aguardando Liquidação Custódia"
                        },
                        new
                        {
                            Id = (short)8,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Em Liquidação Custódia"
                        },
                        new
                        {
                            Id = (short)9,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Cancelada pela Custódia"
                        },
                        new
                        {
                            Id = (short)10,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Aguardando Liquidação Middle"
                        },
                        new
                        {
                            Id = (short)11,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Em Liquidação Middle"
                        },
                        new
                        {
                            Id = (short)12,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Cancelada Middle"
                        },
                        new
                        {
                            Id = (short)13,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Aguardando Registro do Voice"
                        },
                        new
                        {
                            Id = (short)14,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Em Registro do Voice"
                        },
                        new
                        {
                            Id = (short)15,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Cancelado pelo Gestor"
                        },
                        new
                        {
                            Id = (short)16,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Concluído"
                        },
                        new
                        {
                            Id = (short)17,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            Name = "Pendente aprovação do Gestor"
                        });
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowStepResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("ChangeDate");

                    b.Property<string>("ChangeUser");

                    b.Property<DateTimeOffset>("CreationDate");

                    b.Property<string>("CreationUser");

                    b.Property<bool>("IsFirstStep");

                    b.Property<int?>("NextStepApprovedId");

                    b.Property<int?>("NextStepRejectedId");

                    b.Property<int>("StepOriginId");

                    b.Property<int?>("WorkflowId");

                    b.Property<short?>("WorkflowStatusId");

                    b.HasKey("Id");

                    b.HasIndex("NextStepApprovedId");

                    b.HasIndex("NextStepRejectedId");

                    b.HasIndex("StepOriginId");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("WorkflowStatusId");

                    b.ToTable("StepResult","Workflow");
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("ChangeDate");

                    b.Property<string>("ChangeUser");

                    b.Property<DateTimeOffset>("CreationDate");

                    b.Property<string>("CreationUser");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Type","Workflow");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            Name = "Fluxo de Boletas de Cotas - CETIP"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            Name = "Fluxo de Renda Fixa Privada"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            Name = "Fluxo de Renda Fixa Pública"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            Name = "Fluxo de Compromissada de Compra"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            Name = "Fluxo de Swap CETIP"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            Name = "Fluxo de Margem"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            Name = "Fluxo de Termo de Moeda"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            Name = "Fluxo de Boletas de Cotas - TED"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = false,
                            Name = "Fluxo de Boletas de Cotas - CETIP Voice"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            Name = "Fluxo de Futuros BMF"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            Name = "Fluxo de Margem Renda Variável"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            Name = "Fluxo de Margem Dinheiro"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTimeOffset(new DateTime(2019, 6, 4, 15, 40, 44, 688, DateTimeKind.Unspecified), new TimeSpan(0, -3, 0, 0, 0)),
                            CreationUser = "admin",
                            IsActive = true,
                            Name = "Fluxo de Renda Variável"
                        });
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.Workflow", b =>
                {
                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowStepResult", "CurrentStep")
                        .WithMany()
                        .HasForeignKey("CurrentStepId");

                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowType")
                        .WithMany("Workflows")
                        .HasForeignKey("WorkflowTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApprovalRole", b =>
                {
                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApproval", "Approval")
                        .WithMany()
                        .HasForeignKey("ApprovalId");

                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApprovalStep")
                        .WithMany("Approvals")
                        .HasForeignKey("WorkflowApprovalStepId");
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApprovalStep", b =>
                {
                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApprovalStep", "NextStepApproved")
                        .WithMany()
                        .HasForeignKey("NextStepApprovedId");

                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApprovalStep", "NextStepRejected")
                        .WithMany()
                        .HasForeignKey("NextStepRejectedId");

                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowStatus", "WorkflowStatus")
                        .WithMany()
                        .HasForeignKey("WorkflowStatusId");

                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowType")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowTypeId");
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApprovalStepResult", b =>
                {
                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApproval", "Approval")
                        .WithMany()
                        .HasForeignKey("ApprovalId");

                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowStepResult")
                        .WithMany("Approvals")
                        .HasForeignKey("WorkflowStepResultId");
                });

            modelBuilder.Entity("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowStepResult", b =>
                {
                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowStepResult", "NextStepApproved")
                        .WithMany()
                        .HasForeignKey("NextStepApprovedId");

                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowStepResult", "NextStepRejected")
                        .WithMany()
                        .HasForeignKey("NextStepRejectedId");

                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowApprovalStep", "Origin")
                        .WithMany()
                        .HasForeignKey("StepOriginId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId");

                    b.HasOne("Solve.FinancialMarketIntegration.API.Areas.WK.Entities.WorkflowStatus", "WorkflowStatus")
                        .WithMany()
                        .HasForeignKey("WorkflowStatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
