version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
    volumes:
      - esdata:/usr/share/elasticsearch/data
#    networks:
#      - esnetwork
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - "5601:5601"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    networks:
#      - esnetwork
    depends_on:
      - elasticsearch
volumes:
    esdata:
        driver: local
#networks:
#    esnetwork:
#        driver: bridge

